Correção obrigatoriedade
lucasmro/ClearSale pull request #14
Opened 2016-11-22 19:09 UTC by maxmilhas

Esta PR corrige o problema que ocorria quando passamos letras no número do endereço.

2016-11-22 23:20 UTC, lucasmro commented on src/ClearSale/XmlEntity/SendOrder/Address.php
> +        $this->number = "$number";
Talvez fazer um cast explícito com o (string) ao invés de encapsular a variável com aspas duplas seja melhor, não acha?
$this->number = (string) $number;
Fonte: http://www.php.net/manual/en/language.types.string.php#language.types.string.casting

2016-11-23 17:27 UTC, lucasmro requested changes
Por favor, olhe meu comentário sobre o cast para string. Acho que faz mais sentido nesse padrão, daí já aprovo a PR. Obrigado.

2016-11-23 19:37 UTC, byjg commented
Ola, fiz o ajuste solicitado. Testes unitários passados.

2016-11-24 10:49 UTC, lucasmro commented
Opa, show de bola!
Assim que der eu aprovo e passo a tag.
Abraços



 Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=lucasmro@gmail.com&idSignature=22>


--

Lucas Michelini Reis de Oliveira
[ Gtalk ] lucasmro@gmail.com
[ Skype ] lucasmro

On Wed, Nov 23, 2016 at 5:37 PM, Joao Gilberto Magalhães <
notifications@github.com> wrote:

> Ola, fiz o ajuste solicitado. Testes unitários passados.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lucasmro/ClearSale/pull/14#issuecomment-262611435>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB_cCQtmo-3pttpklaLOh_dSNwvKnhegks5rBJXwgaJpZM4K50sF>
> .
>

2016-11-28 10:35 UTC, merged

2016-12-05 12:05 UTC, byjg commented
OI Lucas!!! Eu vi que vc gerou o tag 1.6.0. Isso vai fazer com que a gente mude todo o sistema para suportar a nova versão. Como a mudança foi bem pequena, não seria possível gerar o tag 1.5.1 ao invés do tag 1.6.0?

2016-12-05 15:07 UTC, lucasmro commented
Desculpe, mas não entendi o seu problema. No composer você já não faz referência a tag 1.5.0 dessa biblioteca, para garantir a compatibilidade do sistema? Se fosse 1.5.1 ao invés de 1.6.0 faria alguma diferença?

2016-12-05 15:18 UTC, byjg commented
Sim.

Nós colocamos a versão no composer 1.5.*

Seguimos o padrão de versionamento semântico;

Major.minor.patch

Onde


   1. versão Maior(MAJOR): quando fizer mudanças incompatíveis na API,
   2. versão Menor(MINOR): quando adicionar funcionalidades mantendo
   compatibilidade, e
   3. versão de Correção(PATCH): quando


Veja mais em:
http://semver.org/lang/pt-BR/

Em 5 de dez de 2016 1:07 PM, "Lucas Michelini Reis de Oliveira" <
notifications@github.com> escreveu:

> Desculpe, mas não entendi o seu problema. No composer você já não faz
> referência a tag 1.5.0 dessa biblioteca, para garantir a compatibilidade do
> sistema? Se fosse 1.5.1 ao invés de 1.6.0 faria alguma diferença?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lucasmro/ClearSale/pull/14#issuecomment-264877579>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA77pP_PcJYNjw-cxaNSzFc34nuqBNpAks5rFCiYgaJpZM4K50sF>
> .
>

2016-12-05 15:57 UTC, lucasmro commented
Sim, estou familiarizado com esse padrão.
Concordo com você que a mudança foi pequena e eu poderia ter alterado somente o patch ao invés do minor. Em próximas versões ficarei mais atento para seguir sua sugestão.
Eu não gostaria de apagar essa tag agora, pois não sei se alguém já está utilizando.
Em todo o caso, já que está em 1.6.0, não vejo como isso possa ser uma impacto tão grande no seu sistema. Você não pode alterar seu composer apenas para usar a versão 1.6.* onde hoje está 1.5.*? Vai mudar muita coisa?

2016-12-05 16:01 UTC, byjg commented
Não, sem problemas.

Mas obrigado mesmo assim

Em 5 de dez de 2016 1:57 PM, "Lucas Michelini Reis de Oliveira" <
notifications@github.com> escreveu:

> Sim, estou familiarizado com esse padrão.
> Concordo com você que a mudança foi pequena e eu poderia ter alterado
> somente o patch ao invés do minor. Em próximas versões ficarei mais atento
> para seguir sua sugestão.
> Eu não gostaria de apagar essa tag agora, pois não sei se alguém já está
> utilizando.
> Em todo o caso, já que está em 1.6.0, não vejo como isso possa ser uma
> impacto tão grande no seu sistema. Você não pode alterar seu composer
> apenas para usar a versão 1.6.* onde hoje está 1.5.*? Vai mudar muita coisa?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/lucasmro/ClearSale/pull/14#issuecomment-264891995>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA77pIzkf5q5s6I-XBS98PWiNIwWTgpMks5rFDRcgaJpZM4K50sF>
> .
>